name: Run MongoDB Server
description: Runs MongoDB Server using a method appropriate for the target platform
inputs:
  connection-string-name:
    description: Name of the output environment variable that will receive the connection string
    required: false
    default: "MongoDBConnectionString"

  mongodb-replica-set:
    description: "MongoDB replica set name (no replica set by default)"
    required: false
    default: ""
    
  mongodb-version:
    description: "MongoDB version (default 7.0.6)"
    required: false
    default: "7.0.6"  

  mongodb-port:
    description: "MongoDB port to use (default 27017)"
    required: false
    default: 27017

runs:
  using: "composite"
  steps:
    - name: Install MongoDB Server (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $databaseServiceName = "MongoDB$(Get-Random)"
        echo "::group:: Starting MongoDB $databaseServiceName on port ${{ inputs.mongodb-port }}"
        $replicaSet = "${{ inputs.mongodb-replica-set }}"

        if($replicaSet) {
          echo "Starting MongoD with replica"
          docker run --name $databaseServiceName --publish ${{ inputs.mongodb-port }}:${{ inputs.mongodb-port }} --detach mongo:${{ inputs.mongodb-version }} --replSet $replicaSet --port ${{ inputs.mongodb-port }}
          docker exec --tty $databaseServiceName mongosh --port ${{ inputs.mongodb-port }} --eval "rs.initiate()"
        }
        else {
          echo "Starting MongoD without replica"
          docker run --name $databaseServiceName --publish ${{ inputs.mongodb-port }}:${{ inputs.mongodb-port }} --detach mongo:${{ inputs.mongodb-version }} --port ${{ inputs.mongodb-port }}
        }

    - name: Start MongoDB Server (Linux)
      if: runner.os == 'Linux'
      uses: supercharge/mongodb-github-action@v1.10.0
      with:
        mongodb-replica-set: ${{ inputs.mongodb-replica-set }}
        mongodb-port: ${{ inputs.mongodb-port }}
        mongodb-version: ${{ inputs.mongodb-version }}
    - name: Setup Connection string
      shell: pwsh
      run: |
        echo "Setting environment variable ${{ inputs.connection-string-name }} to MongoDB connection string..."
        echo "${{ inputs.connection-string-name }}=mongodb://127.0.0.1:${{ inputs.mongodb-port }}" >> $Env:GITHUB_ENV
