name: Run MongoDB Server
description: Runs MongoDB Server using a method appropriate for the target platform
inputs:
  connection-string-name:
    description: Name of the output environment variable that will receive the connection string
    required: false
    default: "MongoDBConnectionString"

  mongodb-replica-set:
    description: "MongoDB replica set name (no replica set by default)"
    required: false
    default: ""
    
  mongodb-version:
    description: "MongoDB version (default 7.0.1)"
    required: false
    default: "7.0.1"  

  mongodb-port:
    description: "MongoDB port to use (default 27017)"
    required: false
    default: 27017

runs:
  using: "composite"
  steps:
    - name: Install MongoDB Server (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $databaseServiceName = "MongoDB$(Get-Random)"
        $databaseRootDirectory = "D:\temp\$databaseServiceName"
        $databaseDataDirectory = "$databaseRootDirectory\data"
        $databaseLogsDirectory = "$databaseRootDirectory\logs"
        mkdir $databaseRootDirectory > $null
        mkdir $databaseDataDirectory > $null
        mkdir $databaseLogsDirectory > $null
        
        $version = [Version]::new("${{ inputs.mongodb-version }}")
        $databaseBinDirectory = "C:\Program Files\MongoDB\Server\$($version.Major).$($version.Minor)\bin"

        echo "::group:: Installing MongoDB $version to $databaseBinDirectory"

        choco install mongodb --version=""${{ inputs.mongodb-version }}"" -y --no-progress

        echo "::endgroup::"

        echo "::group:: Starting MongoDB $databaseServiceName on port ${{ inputs.mongodb-port }}"
        $replicaSet = "${{ inputs.mongodb-replica-set }}"

        if($replicaSet) {
          echo "Starting MongoD with replica"
          & "$databaseBinDirectory\mongod.exe" --dbpath $databaseDataDirectory --logpath ""$databaseLogsDirectory\logs.txt"" --port ${{ inputs.mongodb-port }} --bind_ip 127.0.0.1 --install --serviceName $databaseServiceName --serviceDisplayName $databaseServiceName --replSet $replicaSet
        }
        else {
          echo "Starting MongoD without replica"
          & "$databaseBinDirectory\mongod.exe" --dbpath $databaseDataDirectory --logpath ""$databaseLogsDirectory\logs.txt"" --port ${{ inputs.mongodb-port }} --bind_ip 127.0.0.1 --install --serviceName $databaseServiceName --serviceDisplayName $databaseServiceName
        }

        net start $databaseServiceName

        echo "::endgroup::"

        echo "::endgroup::"

        echo "::group::Installing MongoDB Shell"

        choco install mongodb-shell -y --no-progress

        echo "::endgroup::"

        if($replicaSet) {
          & mongosh "mongodb://127.0.0.1:${{ inputs.mongodb-port }}" --eval "rs.initiate()"
        }

    - name: Start MongoDB Server (Linux)
      if: runner.os == 'Linux'
      uses: supercharge/mongodb-github-action@v1.10.0
      with:
        mongodb-replica-set: ${{ inputs.mongodb-replica-set }}
        mongodb-port: ${{ inputs.mongodb-port }}
        mongodb-version: ${{ inputs.mongodb-version }}
    - name: Setup Connection string
      shell: pwsh
      run: |
        echo "Setting environment variable ${{ inputs.connection-string-name }} to MongoDB connection string..."
        echo "${{ inputs.connection-string-name }}=mongodb://127.0.0.1:${{ inputs.mongodb-port }}" >> $Env:GITHUB_ENV
